<?php

use Illuminate\Database\Seeder;

class EventsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('events')->delete();
        
        \DB::table('events')->insert(array (
            0 => 
            array (
                'id' => 29,
                'course_instance_id' => 58,
                'class_size' => 10,
                'public_comments' => 'MLK Day Holiday',
                'internal_comments' => NULL,
                'start_time' => '2019-01-21 10:00:00',
                'end_time' => '2019-01-21 11:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 49,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-17 15:18:28',
                'updated_at' => '2019-01-17 15:18:28',
            ),
            1 => 
            array (
                'id' => 30,
                'course_instance_id' => 59,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>Catering is required for breakfast.&nbsp; Setup in Classroom B.</p>',
                'start_time' => '2019-04-15 09:00:00',
                'end_time' => '2019-04-15 15:00:00',
                'setup_time' => 45,
                'teardown_time' => 30,
                'fac_report' => 15,
                'fac_leave' => -15,
                'initial_meeting_room' => 45,
            'color' => 'rgb(0, 0, 255)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-17 15:33:46',
                'updated_at' => '2019-01-17 15:33:46',
            ),
            2 => 
            array (
                'id' => 31,
                'course_instance_id' => 60,
                'class_size' => 10,
                'public_comments' => 'Change Init Meeting Room',
                'internal_comments' => NULL,
                'start_time' => '2019-04-16 10:00:00',
                'end_time' => '2019-04-16 11:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 74,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-17 15:46:11',
                'updated_at' => '2019-01-17 15:46:11',
            ),
            3 => 
            array (
                'id' => 35,
                'course_instance_id' => 64,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-26 08:00:00',
                'end_time' => '2019-04-26 11:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 58,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 16:01:56',
                'updated_at' => '2019-01-22 16:01:56',
            ),
            4 => 
            array (
                'id' => 36,
                'course_instance_id' => 65,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. Same set up as this year please.</p>',
                'start_time' => '2019-06-04 13:00:00',
                'end_time' => '2019-06-04 17:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 45,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 16:42:36',
                'updated_at' => '2019-01-22 16:42:36',
            ),
            5 => 
            array (
                'id' => 37,
                'course_instance_id' => 66,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. Same set up as this year please.</p>',
                'start_time' => '2019-06-05 13:00:00',
                'end_time' => '2019-06-05 17:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 19:24:48',
                'updated_at' => '2019-01-22 19:24:48',
            ),
            6 => 
            array (
                'id' => 38,
                'course_instance_id' => 67,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. Same set up as this year please.</p>',
                'start_time' => '2019-06-06 13:00:00',
                'end_time' => '2019-06-06 17:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 45,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 19:26:20',
                'updated_at' => '2019-01-22 19:26:20',
            ),
            7 => 
            array (
                'id' => 39,
                'course_instance_id' => 68,
                'class_size' => 10,
                'public_comments' => 'Test',
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. East Only</p>',
                'start_time' => '2019-05-16 08:00:00',
                'end_time' => '2019-05-16 13:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 147,
            'color' => 'rgb(59, 255, 10)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 19:47:20',
                'updated_at' => '2019-01-22 19:47:20',
            ),
            8 => 
            array (
                'id' => 40,
                'course_instance_id' => 69,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. ACLS Renewal Class. SIM specialist needed to start at 10:00 a.m.</p>',
                'start_time' => '2019-04-22 08:00:00',
                'end_time' => '2019-04-22 14:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 147,
            'color' => 'rgb(59, 255, 10)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 20:00:12',
                'updated_at' => '2019-01-22 20:00:12',
            ),
            9 => 
            array (
                'id' => 41,
                'course_instance_id' => 70,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. East Only</p>',
                'start_time' => '2019-06-13 08:00:00',
                'end_time' => '2019-06-13 13:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 147,
            'color' => 'rgb(59, 255, 10)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 20:01:16',
                'updated_at' => '2019-01-22 20:01:16',
            ),
            10 => 
            array (
                'id' => 42,
                'course_instance_id' => 71,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. East Only</p>',
                'start_time' => '2019-07-11 01:00:00',
                'end_time' => '2019-07-11 13:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 147,
            'color' => 'rgb(59, 255, 10)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 20:02:13',
                'updated_at' => '2019-01-22 20:02:13',
            ),
            11 => 
            array (
                'id' => 43,
                'course_instance_id' => 72,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. East Only</p>',
                'start_time' => '2019-07-09 01:00:00',
                'end_time' => '2019-07-09 13:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 147,
            'color' => 'rgb(59, 255, 10)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 20:03:11',
                'updated_at' => '2019-01-22 20:03:11',
            ),
            12 => 
            array (
                'id' => 44,
                'course_instance_id' => 73,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. East Only</p>',
                'start_time' => '2019-09-05 08:00:00',
                'end_time' => '2019-09-05 13:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 147,
            'color' => 'rgb(59, 255, 10)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 20:04:21',
                'updated_at' => '2019-01-22 20:04:21',
            ),
            13 => 
            array (
                'id' => 45,
                'course_instance_id' => 74,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. 2 classrooms and 4 sim rooms</p>',
                'start_time' => '2019-07-19 08:00:00',
                'end_time' => '2019-07-19 16:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 21:45:51',
                'updated_at' => '2019-01-22 21:45:51',
            ),
            14 => 
            array (
                'id' => 46,
                'course_instance_id' => 75,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. Classroom A and B and 4 Met Rooms</p>',
                'start_time' => '2019-07-25 08:00:00',
                'end_time' => '2019-07-25 16:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 21:59:39',
                'updated_at' => '2019-01-22 21:59:39',
            ),
            15 => 
            array (
                'id' => 47,
                'course_instance_id' => 76,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. Classroom b and 5 sim rooms if possible</p>',
                'start_time' => '2019-07-26 08:00:00',
                'end_time' => '2019-07-26 16:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 45,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 22:02:08',
                'updated_at' => '2019-01-22 22:02:08',
            ),
            16 => 
            array (
                'id' => 48,
                'course_instance_id' => 77,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. Classroom A and B and 4 Met Rooms</p>',
                'start_time' => '2019-08-01 08:00:00',
                'end_time' => '2019-08-01 16:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 22:03:31',
                'updated_at' => '2019-01-22 22:03:31',
            ),
            17 => 
            array (
                'id' => 49,
                'course_instance_id' => 78,
                'class_size' => 10,
                'public_comments' => 'Remember to wear scrubs',
                'internal_comments' => '<p>Catering - Jimmy Johns, delivery at 11:30 am</p>',
                'start_time' => '2019-04-17 09:00:00',
                'end_time' => '2019-04-17 15:00:00',
                'setup_time' => 30,
                'teardown_time' => 45,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-23 19:09:20',
                'updated_at' => '2019-01-23 19:09:20',
            ),
            18 => 
            array (
                'id' => 50,
                'course_instance_id' => 79,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-04-17 10:00:00',
                'end_time' => '2019-04-17 14:00:00',
                'setup_time' => 45,
                'teardown_time' => 30,
                'fac_report' => 15,
                'fac_leave' => -15,
                'initial_meeting_room' => 46,
            'color' => 'rgb(255, 0, 0)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-23 20:01:58',
                'updated_at' => '2019-01-23 20:01:58',
            ),
            19 => 
            array (
                'id' => 51,
                'course_instance_id' => 80,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-18 10:45:00',
                'end_time' => '2019-04-18 12:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 147,
            'color' => 'rgb(110, 255, 250)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 13:33:58',
                'updated_at' => '2019-01-24 13:33:58',
            ),
            20 => 
            array (
                'id' => 52,
                'course_instance_id' => 81,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-05-16 10:45:00',
                'end_time' => '2019-05-16 12:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 148,
            'color' => 'rgb(110, 255, 250)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 13:52:14',
                'updated_at' => '2019-01-24 13:52:14',
            ),
            21 => 
            array (
                'id' => 53,
                'course_instance_id' => 82,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. Met 11</p>',
                'start_time' => '2019-04-18 13:00:00',
                'end_time' => '2019-04-18 14:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 58,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:00:09',
                'updated_at' => '2019-01-24 14:00:09',
            ),
            22 => 
            array (
                'id' => 54,
                'course_instance_id' => 83,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>-jl testing eye tracking software</p>',
                'start_time' => '2019-04-18 09:00:00',
                'end_time' => '2019-04-18 11:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 58,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:01:51',
                'updated_at' => '2019-01-24 14:01:51',
            ),
            23 => 
            array (
                'id' => 55,
                'course_instance_id' => 84,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. classroom</p>',
                'start_time' => '2019-04-17 07:30:00',
                'end_time' => '2019-04-17 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 149,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:11:08',
                'updated_at' => '2019-01-24 14:11:08',
            ),
            24 => 
            array (
                'id' => 56,
                'course_instance_id' => 85,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. classroom</p>',
                'start_time' => '2019-04-18 07:30:00',
                'end_time' => '2019-04-18 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 149,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:11:55',
                'updated_at' => '2019-01-24 14:11:55',
            ),
            25 => 
            array (
                'id' => 57,
                'course_instance_id' => 86,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. classroom</p>',
                'start_time' => '2019-04-19 07:30:00',
                'end_time' => '2019-04-19 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 149,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:12:30',
                'updated_at' => '2019-01-24 14:12:30',
            ),
            26 => 
            array (
                'id' => 58,
                'course_instance_id' => 87,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-04-18 14:00:00',
                'end_time' => '2019-04-18 14:30:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 1,
            'color' => 'rgb(255, 233, 33)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:14:13',
                'updated_at' => '2019-01-24 14:14:13',
            ),
            27 => 
            array (
                'id' => 59,
                'course_instance_id' => 88,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>PM\'s and room clean up</p>',
                'start_time' => '2019-04-18 07:30:00',
                'end_time' => '2019-04-18 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 76,
            'color' => 'rgb(202, 68, 207)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:16:09',
                'updated_at' => '2019-01-24 14:16:09',
            ),
            28 => 
            array (
                'id' => 60,
                'course_instance_id' => 89,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>HAP - DOH planning meeting DF, EP, KW</p>',
                'start_time' => '2019-04-19 09:00:00',
                'end_time' => '2019-04-19 10:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 72,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:18:03',
                'updated_at' => '2019-01-24 14:18:03',
            ),
            29 => 
            array (
                'id' => 61,
                'course_instance_id' => 90,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. MWH 4225</p>',
                'start_time' => '2019-04-19 09:15:00',
                'end_time' => '2019-04-19 10:15:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => -15,
                'fac_leave' => 15,
                'initial_meeting_room' => 150,
            'color' => 'rgb(255, 179, 247)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:22:14',
                'updated_at' => '2019-01-24 14:22:14',
            ),
            30 => 
            array (
                'id' => 62,
                'course_instance_id' => 91,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. MWH 4225</p>',
                'start_time' => '2019-04-19 10:15:00',
                'end_time' => '2019-04-19 11:15:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => -15,
                'fac_leave' => 15,
                'initial_meeting_room' => 150,
            'color' => 'rgb(255, 179, 247)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:29:20',
                'updated_at' => '2019-01-24 14:29:20',
            ),
            31 => 
            array (
                'id' => 63,
                'course_instance_id' => 92,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. mwh 4225</p>',
                'start_time' => '2019-04-19 12:30:00',
                'end_time' => '2019-04-19 13:30:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => -15,
                'fac_leave' => 15,
                'initial_meeting_room' => 150,
            'color' => 'rgb(255, 179, 247)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:30:51',
                'updated_at' => '2019-01-24 14:30:51',
            ),
            32 => 
            array (
                'id' => 64,
                'course_instance_id' => 93,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. mwh offsite in ICU after First 5</p>',
                'start_time' => '2019-04-19 14:00:00',
                'end_time' => '2019-04-19 15:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => -15,
                'fac_leave' => 15,
                'initial_meeting_room' => 150,
            'color' => 'rgb(255, 179, 247)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:34:48',
                'updated_at' => '2019-01-24 14:34:48',
            ),
            33 => 
            array (
                'id' => 65,
                'course_instance_id' => 94,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>HAP - DOH project - DF, EP, MA</p>',
                'start_time' => '2019-04-19 13:00:00',
                'end_time' => '2019-04-19 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 72,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:36:10',
                'updated_at' => '2019-01-24 14:36:10',
            ),
            34 => 
            array (
                'id' => 67,
                'course_instance_id' => 96,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-04-19 15:00:00',
                'end_time' => '2019-04-19 17:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 48,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:40:14',
                'updated_at' => '2019-01-24 14:40:14',
            ),
            35 => 
            array (
                'id' => 68,
                'course_instance_id' => 97,
                'class_size' => 10,
                'public_comments' => NULL,
            'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. 2 briefing rooms (CL A, CL B), 6 MET encounter rooms. Proctor needs a table and chair in the hallway to monitor transitions between stations.</p>',
                'start_time' => '2019-04-19 07:00:00',
                'end_time' => '2019-04-19 12:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 45,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:44:20',
                'updated_at' => '2019-01-24 14:44:20',
            ),
            36 => 
            array (
                'id' => 69,
                'course_instance_id' => 98,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. MET 8-9. HOCUS POCUS room set up. Please schedule for partial time if entire slot is unavailable.</p>',
                'start_time' => '2019-04-19 10:00:00',
                'end_time' => '2019-04-19 12:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => -15,
                'fac_leave' => 0,
                'initial_meeting_room' => 57,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:48:35',
                'updated_at' => '2019-01-24 14:48:35',
            ),
            37 => 
            array (
                'id' => 70,
                'course_instance_id' => 99,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-20 07:00:00',
                'end_time' => '2019-04-20 12:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:52:07',
                'updated_at' => '2019-01-24 14:52:07',
            ),
            38 => 
            array (
                'id' => 71,
                'course_instance_id' => 100,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>HAP EVOLVE orientation - EP</p>',
                'start_time' => '2019-04-22 08:00:00',
                'end_time' => '2019-04-22 10:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 72,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:55:27',
                'updated_at' => '2019-01-24 14:55:27',
            ),
            39 => 
            array (
                'id' => 72,
                'course_instance_id' => 101,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. class will start promptly at 8:35</p>',
                'start_time' => '2019-04-22 08:30:00',
                'end_time' => '2019-04-22 12:00:00',
                'setup_time' => 30,
                'teardown_time' => 0,
                'fac_report' => -15,
                'fac_leave' => 0,
                'initial_meeting_room' => 148,
            'color' => 'rgb(110, 255, 250)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:59:08',
                'updated_at' => '2019-01-24 14:59:08',
            ),
            40 => 
            array (
                'id' => 73,
                'course_instance_id' => 102,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. classrooms A, B, DB1, Met 7, 3,4,5. need bed, IV tubing and pump, O2, NC,</p>',
                'start_time' => '2019-04-22 09:00:00',
                'end_time' => '2019-04-22 12:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 15:08:49',
                'updated_at' => '2019-01-24 15:08:49',
            ),
            41 => 
            array (
                'id' => 74,
                'course_instance_id' => 103,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-22 11:00:00',
                'end_time' => '2019-04-22 13:00:00',
                'setup_time' => 30,
                'teardown_time' => 15,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 58,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 15:16:28',
                'updated_at' => '2019-01-24 15:16:28',
            ),
            42 => 
            array (
                'id' => 75,
                'course_instance_id' => 104,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. Will have 1 SP from SoM</p>',
                'start_time' => '2019-04-22 13:00:00',
                'end_time' => '2019-04-22 17:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => -15,
                'fac_leave' => 15,
                'initial_meeting_room' => 53,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 15:18:26',
                'updated_at' => '2019-01-24 15:18:26',
            ),
            43 => 
            array (
                'id' => 76,
                'course_instance_id' => 105,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. CHP Sim Lab</p>',
                'start_time' => '2019-04-23 08:00:00',
                'end_time' => '2019-04-23 11:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 76,
            'color' => 'rgb(202, 68, 207)',
                'sims_spec_needed' => 1,
                'special_requirements' => 1,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 15:29:10',
                'updated_at' => '2019-01-24 15:29:10',
            ),
            44 => 
            array (
                'id' => 77,
                'course_instance_id' => 106,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. MET 10</p>',
                'start_time' => '2019-04-23 11:00:00',
                'end_time' => '2019-04-23 13:00:00',
                'setup_time' => 30,
                'teardown_time' => 15,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 58,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 15:31:28',
                'updated_at' => '2019-01-24 15:31:28',
            ),
            45 => 
            array (
                'id' => 78,
                'course_instance_id' => 107,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. classrooms A, B, DB1, Met 7, 3,4,5. need bed, IV tubing and pump, O2, NC,</p>',
                'start_time' => '2019-04-23 12:30:00',
                'end_time' => '2019-04-23 15:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 15:33:24',
                'updated_at' => '2019-01-24 15:33:24',
            ),
            46 => 
            array (
                'id' => 79,
                'course_instance_id' => 108,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. Will be using SP from SoM</p>',
                'start_time' => '2019-03-11 13:00:00',
                'end_time' => '2019-03-11 15:30:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => -15,
                'fac_leave' => 0,
                'initial_meeting_room' => 50,
                'color' => NULL,
                'sims_spec_needed' => 1,
                'special_requirements' => 1,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 15:36:12',
                'updated_at' => '2019-01-24 15:36:12',
            ),
            47 => 
            array (
                'id' => 80,
                'course_instance_id' => 109,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-23 13:00:00',
                'end_time' => '2019-04-23 15:00:00',
                'setup_time' => 30,
                'teardown_time' => 15,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 60,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 15:37:54',
                'updated_at' => '2019-01-24 15:37:54',
            ),
            48 => 
            array (
                'id' => 81,
                'course_instance_id' => 110,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-23 13:00:00',
                'end_time' => '2019-04-23 15:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 150,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 15:39:19',
                'updated_at' => '2019-02-11 17:14:53',
            ),
            49 => 
            array (
                'id' => 82,
                'course_instance_id' => 111,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-23 13:30:00',
                'end_time' => '2019-04-23 17:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 48,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:06:56',
                'updated_at' => '2019-01-24 16:06:56',
            ),
            50 => 
            array (
                'id' => 83,
                'course_instance_id' => 112,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. Mock code on floor; will know room day of; will meet sim spec at 2:30 in sim room</p>',
                'start_time' => '2019-04-23 14:30:00',
                'end_time' => '2019-04-23 16:00:00',
                'setup_time' => 30,
                'teardown_time' => 15,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 76,
            'color' => 'rgb(202, 68, 207)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:18:14',
                'updated_at' => '2019-01-24 16:18:14',
            ),
            51 => 
            array (
                'id' => 84,
                'course_instance_id' => 113,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. MWH 4225</p>',
                'start_time' => '2019-04-23 16:15:00',
                'end_time' => '2019-04-23 17:15:00',
                'setup_time' => 30,
                'teardown_time' => 0,
                'fac_report' => 15,
                'fac_leave' => 15,
                'initial_meeting_room' => 150,
            'color' => 'rgb(255, 179, 247)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:21:52',
                'updated_at' => '2019-01-24 16:21:52',
            ),
            52 => 
            array (
                'id' => 85,
                'course_instance_id' => 114,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. MWH 4225</p>',
                'start_time' => '2019-04-23 17:15:00',
                'end_time' => '2019-04-23 18:15:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 15,
                'fac_leave' => 15,
                'initial_meeting_room' => 150,
            'color' => 'rgb(255, 179, 247)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:22:49',
                'updated_at' => '2019-01-24 16:22:49',
            ),
            53 => 
            array (
                'id' => 86,
                'course_instance_id' => 115,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-24 07:00:00',
                'end_time' => '2019-04-24 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 149,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:34:37',
                'updated_at' => '2019-01-24 16:34:37',
            ),
            54 => 
            array (
                'id' => 87,
                'course_instance_id' => 116,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-24 07:00:00',
                'end_time' => '2019-04-24 16:00:00',
                'setup_time' => 30,
                'teardown_time' => 0,
                'fac_report' => 15,
                'fac_leave' => 15,
                'initial_meeting_room' => 79,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:37:39',
                'updated_at' => '2019-01-24 16:37:39',
            ),
            55 => 
            array (
                'id' => 88,
                'course_instance_id' => 117,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. Will be using SP from SoM</p>',
                'start_time' => '2019-04-24 08:00:00',
                'end_time' => '2019-04-24 11:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => -15,
                'fac_leave' => 15,
                'initial_meeting_room' => 58,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:41:58',
                'updated_at' => '2019-01-24 16:41:58',
            ),
            56 => 
            array (
                'id' => 89,
                'course_instance_id' => 118,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. classrooms A, B, DB1, Met 7, 3,4,5. need bed, IV tubing and pump, O2, NC,</p>',
                'start_time' => '2019-04-24 09:00:00',
                'end_time' => '2019-04-24 12:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:43:27',
                'updated_at' => '2019-01-24 16:43:27',
            ),
            57 => 
            array (
                'id' => 90,
                'course_instance_id' => 119,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. ACLS Mega Code testing.</p>',
                'start_time' => '2019-04-24 09:00:00',
                'end_time' => '2019-04-24 11:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 148,
            'color' => 'rgb(18, 200, 255)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:45:00',
                'updated_at' => '2019-01-24 16:45:00',
            ),
            58 => 
            array (
                'id' => 91,
                'course_instance_id' => 120,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-24 10:00:00',
                'end_time' => '2019-04-24 12:00:00',
                'setup_time' => 30,
                'teardown_time' => 15,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 58,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:47:14',
                'updated_at' => '2019-01-24 16:47:14',
            ),
            59 => 
            array (
                'id' => 92,
                'course_instance_id' => 121,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. same participants</p>',
                'start_time' => '2019-04-24 10:00:00',
                'end_time' => '2019-04-24 11:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 147,
            'color' => 'rgb(255, 31, 105)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:49:17',
                'updated_at' => '2019-01-24 16:49:17',
            ),
            60 => 
            array (
                'id' => 93,
                'course_instance_id' => 122,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. Met 12 &amp; 13, HOCUS POCUS study</p>',
                'start_time' => '2019-04-24 10:30:00',
                'end_time' => '2019-04-24 14:30:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 60,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:51:15',
                'updated_at' => '2019-01-24 16:51:15',
            ),
            61 => 
            array (
                'id' => 94,
                'course_instance_id' => 123,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. MET 10</p>',
                'start_time' => '2019-04-24 11:00:00',
                'end_time' => '2019-04-24 13:00:00',
                'setup_time' => 30,
                'teardown_time' => 15,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 57,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 16:58:14',
                'updated_at' => '2019-01-24 16:58:14',
            ),
            62 => 
            array (
                'id' => 95,
                'course_instance_id' => 124,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. 2 sessions, 2 hours per session, 2-3 participants per session</p>',
                'start_time' => '2019-04-24 12:00:00',
                'end_time' => '2019-04-24 14:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 151,
            'color' => 'rgb(18, 200, 255)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:04:44',
                'updated_at' => '2019-01-24 17:04:44',
            ),
            63 => 
            array (
                'id' => 96,
                'course_instance_id' => 125,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. MET 10</p>',
                'start_time' => '2019-04-24 13:00:00',
                'end_time' => '2019-04-24 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:06:19',
                'updated_at' => '2019-01-24 17:06:19',
            ),
            64 => 
            array (
                'id' => 97,
                'course_instance_id' => 126,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. same participants</p>',
                'start_time' => '2019-04-24 13:00:00',
                'end_time' => '2019-04-24 14:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 147,
            'color' => 'rgb(255, 31, 105)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:08:51',
                'updated_at' => '2019-01-24 17:08:51',
            ),
            65 => 
            array (
                'id' => 98,
                'course_instance_id' => 127,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. 2 sessions, 2 hours per session, 2-3 participants per session</p>',
                'start_time' => '2019-04-24 14:00:00',
                'end_time' => '2019-04-24 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 151,
            'color' => 'rgb(18, 200, 255)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:10:20',
                'updated_at' => '2019-01-24 17:10:20',
            ),
            66 => 
            array (
                'id' => 99,
                'course_instance_id' => 128,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. as above</p>',
                'start_time' => '2019-04-24 17:00:00',
                'end_time' => '2019-04-24 18:45:00',
                'setup_time' => 30,
                'teardown_time' => 0,
                'fac_report' => -15,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:17:16',
                'updated_at' => '2019-01-24 17:17:16',
            ),
            67 => 
            array (
                'id' => 100,
                'course_instance_id' => 129,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-24 18:00:00',
                'end_time' => '2019-04-24 22:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:18:27',
                'updated_at' => '2019-01-24 17:18:27',
            ),
            68 => 
            array (
                'id' => 101,
                'course_instance_id' => 130,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>PM\'s and room clean up</p>',
                'start_time' => '2019-04-25 07:30:00',
                'end_time' => '2019-04-25 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 76,
            'color' => 'rgb(202, 68, 207)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:31:10',
                'updated_at' => '2019-01-24 17:31:10',
            ),
            69 => 
            array (
                'id' => 102,
                'course_instance_id' => 131,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. Met 12 &amp; 13, HOCUS POCUS study</p>',
                'start_time' => '2019-04-25 09:00:00',
                'end_time' => '2019-04-25 10:30:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 60,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:32:56',
                'updated_at' => '2019-01-24 17:32:56',
            ),
            70 => 
            array (
                'id' => 103,
                'course_instance_id' => 132,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. MET 9</p>',
                'start_time' => '2019-04-25 11:00:00',
                'end_time' => '2019-04-25 12:30:00',
                'setup_time' => 30,
                'teardown_time' => 15,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 58,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:34:46',
                'updated_at' => '2019-01-24 17:34:46',
            ),
            71 => 
            array (
                'id' => 104,
                'course_instance_id' => 133,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED.</p>',
                'start_time' => '2019-04-25 12:00:00',
                'end_time' => '2019-04-25 15:00:00',
                'setup_time' => 45,
                'teardown_time' => 30,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:44:41',
                'updated_at' => '2019-01-24 17:44:41',
            ),
            72 => 
            array (
                'id' => 105,
                'course_instance_id' => 134,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-04-25 12:30:00',
                'end_time' => '2019-04-25 15:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 45,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:46:55',
                'updated_at' => '2019-01-24 17:46:55',
            ),
            73 => 
            array (
                'id' => 106,
                'course_instance_id' => 135,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. classrooms A, B, DB1, Met 7, 3,4,5. need bed, IV tubing and pump, O2, NC,</p>',
                'start_time' => '2019-04-26 09:00:00',
                'end_time' => '2019-04-26 12:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:51:14',
                'updated_at' => '2019-01-24 17:51:14',
            ),
            74 => 
            array (
                'id' => 107,
                'course_instance_id' => 136,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>NO SIMS SPECIALIST NEEDED. Met 12 &amp; 13, HOCUS POCUS study</p>',
                'start_time' => '2019-04-26 10:00:00',
                'end_time' => '2019-04-26 18:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 60,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:52:51',
                'updated_at' => '2019-01-24 17:52:51',
            ),
            75 => 
            array (
                'id' => 108,
                'course_instance_id' => 137,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-04-26 11:00:00',
                'end_time' => '2019-04-26 13:00:00',
                'setup_time' => 30,
                'teardown_time' => 15,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 58,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:54:41',
                'updated_at' => '2019-01-24 17:54:41',
            ),
            76 => 
            array (
                'id' => 109,
                'course_instance_id' => 138,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-04-26 15:00:00',
                'end_time' => '2019-04-26 17:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 48,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:55:56',
                'updated_at' => '2019-01-24 17:55:56',
            ),
            77 => 
            array (
                'id' => 110,
                'course_instance_id' => 139,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. CLASSROOM, LAB 1 AND 2</p>',
                'start_time' => '2019-04-29 10:30:00',
                'end_time' => '2019-04-29 11:30:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 79,
            'color' => 'rgb(44, 130, 12)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:59:34',
                'updated_at' => '2019-01-24 17:59:34',
            ),
            78 => 
            array (
                'id' => 111,
                'course_instance_id' => 140,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>GRR update meeting DF, AT</p>',
                'start_time' => '2019-04-29 12:00:00',
                'end_time' => '2019-04-29 13:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 46,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 18:00:43',
                'updated_at' => '2019-01-24 18:00:43',
            ),
            79 => 
            array (
                'id' => 112,
                'course_instance_id' => 141,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>SIMS SPECIALIST NEEDED. Airlines day: Classroom, Met 10, Met 11, Met 1</p>',
                'start_time' => '2019-04-29 13:00:00',
                'end_time' => '2019-04-29 15:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 18:02:14',
                'updated_at' => '2019-01-24 18:02:14',
            ),
            80 => 
            array (
                'id' => 113,
                'course_instance_id' => 142,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-04-29 15:00:00',
                'end_time' => '2019-04-29 16:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 15,
                'fac_leave' => 15,
                'initial_meeting_room' => 148,
            'color' => 'rgb(255, 31, 105)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 18:03:29',
                'updated_at' => '2019-01-24 18:03:29',
            ),
            81 => 
            array (
                'id' => 114,
                'course_instance_id' => 143,
                'class_size' => 10,
                'public_comments' => 'Public Comment',
                'internal_comments' => NULL,
                'start_time' => '2019-04-30 08:00:00',
                'end_time' => '2019-04-30 16:00:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => -15,
                'fac_leave' => -15,
                'initial_meeting_room' => 79,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 18:05:25',
                'updated_at' => '2019-02-05 14:35:50',
            ),
            82 => 
            array (
                'id' => 115,
                'course_instance_id' => 144,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>PM\'s and room clean up</p>',
                'start_time' => '2019-04-30 07:30:00',
                'end_time' => '2019-04-30 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 76,
            'color' => 'rgb(202, 68, 207)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 18:06:35',
                'updated_at' => '2019-01-24 18:06:35',
            ),
            83 => 
            array (
                'id' => 116,
                'course_instance_id' => 145,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-04-30 10:00:00',
                'end_time' => '2019-04-30 14:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 151,
            'color' => 'rgb(18, 200, 255)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 18:08:15',
                'updated_at' => '2019-01-24 18:08:15',
            ),
            84 => 
            array (
                'id' => 117,
                'course_instance_id' => 146,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-04-30 13:00:00',
                'end_time' => '2019-04-30 14:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 151,
            'color' => 'rgb(18, 200, 255)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 18:09:32',
                'updated_at' => '2019-01-24 18:09:32',
            ),
            85 => 
            array (
                'id' => 128,
                'course_instance_id' => 157,
                'class_size' => 10,
                'public_comments' => 'Test',
                'internal_comments' => NULL,
                'start_time' => '2019-05-16 10:00:00',
                'end_time' => '2019-05-16 11:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 1,
            'color' => 'rgb(255, 153, 0)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-02-07 20:40:55',
                'updated_at' => '2019-02-07 20:40:55',
            ),
            86 => 
            array (
                'id' => 129,
                'course_instance_id' => 158,
                'class_size' => 10,
                'public_comments' => 'today',
                'internal_comments' => NULL,
                'start_time' => '2019-05-02 10:00:00',
                'end_time' => '2019-05-02 11:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 1,
            'color' => 'rgb(0, 0, 255)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-02-07 20:42:20',
                'updated_at' => '2019-02-07 20:42:20',
            ),
            87 => 
            array (
                'id' => 130,
                'course_instance_id' => 159,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-05-02 13:00:00',
                'end_time' => '2019-05-02 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 147,
            'color' => 'rgb(147, 196, 125)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-02-07 20:43:09',
                'updated_at' => '2019-02-07 20:43:09',
            ),
            88 => 
            array (
                'id' => 131,
                'course_instance_id' => 160,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-05-03 10:00:00',
                'end_time' => '2019-05-03 11:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 148,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-02-08 16:19:28',
                'updated_at' => '2019-02-08 16:19:28',
            ),
            89 => 
            array (
                'id' => 132,
                'course_instance_id' => 161,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-05-03 14:00:00',
                'end_time' => '2019-05-03 16:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 1,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-02-08 16:20:35',
                'updated_at' => '2019-02-08 16:20:35',
            ),
            90 => 
            array (
                'id' => 133,
                'course_instance_id' => 162,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-05-03 08:00:00',
                'end_time' => '2019-05-03 17:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 46,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-02-08 16:24:39',
                'updated_at' => '2019-02-08 16:24:39',
            ),
            91 => 
            array (
                'id' => 134,
                'course_instance_id' => 163,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-05-03 10:00:00',
                'end_time' => '2019-05-03 10:30:00',
                'setup_time' => 30,
                'teardown_time' => 30,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 56,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-02-08 16:51:52',
                'updated_at' => '2019-02-08 16:51:52',
            ),
            92 => 
            array (
                'id' => 135,
                'course_instance_id' => 164,
                'class_size' => 10,
                'public_comments' => 'Bring scrubs',
                'internal_comments' => '<p>Pizza for lunch</p>',
                'start_time' => '2019-05-06 10:00:00',
                'end_time' => '2019-05-06 15:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 1,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-02-11 17:25:21',
                'updated_at' => '2019-02-11 17:25:21',
            ),
            93 => 
            array (
                'id' => 137,
                'course_instance_id' => 166,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-05-08 10:00:00',
                'end_time' => '2019-05-08 11:00:00',
                'setup_time' => 15,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 42,
            'color' => 'rgb(56, 118, 29)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-02-13 17:23:36',
                'updated_at' => '2019-02-13 20:57:40',
            ),
            94 => 
            array (
                'id' => 138,
                'course_instance_id' => 167,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-05-09 10:00:00',
                'end_time' => '2019-05-09 11:00:00',
                'setup_time' => 30,
                'teardown_time' => 15,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
            'color' => 'rgb(204, 0, 0)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-02-14 14:47:13',
                'updated_at' => '2019-02-14 14:47:13',
            ),
            95 => 
            array (
                'id' => 139,
                'course_instance_id' => 168,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-05-23 10:00:00',
                'end_time' => '2019-05-23 11:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 1,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-02-28 13:58:53',
                'updated_at' => '2019-02-28 13:58:53',
            ),
            96 => 
            array (
                'id' => 140,
                'course_instance_id' => 169,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>Catering Needed</p>',
                'start_time' => '2019-04-17 10:00:00',
                'end_time' => '2019-04-17 15:00:00',
                'setup_time' => 30,
                'teardown_time' => 15,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 49,
            'color' => 'rgb(255, 153, 0)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-03-04 19:25:19',
                'updated_at' => '2019-03-04 19:27:56',
            ),
            97 => 
            array (
                'id' => 141,
                'course_instance_id' => 170,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => '<p>This is <span style="color: #ff0000;"><strong>sample</strong></span> text.&nbsp;</p>',
                'start_time' => '2019-05-29 10:00:00',
                'end_time' => '2019-05-29 11:00:00',
                'setup_time' => 45,
                'teardown_time' => 30,
                'fac_report' => 15,
                'fac_leave' => -15,
                'initial_meeting_room' => 55,
            'color' => 'rgb(255, 0, 0)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-03-06 15:48:07',
                'updated_at' => '2019-03-06 15:48:07',
            ),
            98 => 
            array (
                'id' => 142,
                'course_instance_id' => 171,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-05-30 10:00:00',
                'end_time' => '2019-05-30 11:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-03-07 15:59:30',
                'updated_at' => '2019-03-07 15:59:30',
            ),
            99 => 
            array (
                'id' => 143,
                'course_instance_id' => 172,
                'class_size' => 10,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-04-17 10:00:00',
                'end_time' => '2019-04-17 11:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 47,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-03-07 16:41:17',
                'updated_at' => '2019-03-07 16:41:17',
            ),
            100 => 
            array (
                'id' => 151,
                'course_instance_id' => 181,
                'class_size' => 1,
                'public_comments' => 'Pitt Spring Break Holiday',
                'internal_comments' => NULL,
                'start_time' => '2019-03-15 08:00:00',
                'end_time' => '2019-03-15 17:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 49,
            'color' => 'rgb(244, 204, 204)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-03-11 19:10:45',
                'updated_at' => '2019-03-11 19:10:45',
            ),
            101 => 
            array (
                'id' => 152,
                'course_instance_id' => 182,
                'class_size' => 1,
                'public_comments' => 'Pitt Spring Break Holiday',
                'internal_comments' => NULL,
                'start_time' => '2019-03-15 08:00:00',
                'end_time' => '2019-03-15 17:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 47,
            'color' => 'rgb(244, 204, 204)',
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-03-11 20:18:40',
                'updated_at' => '2019-03-11 20:18:40',
            ),
            102 => 
            array (
                'id' => 153,
                'course_instance_id' => 183,
                'class_size' => 14,
                'public_comments' => NULL,
                'internal_comments' => NULL,
                'start_time' => '2019-03-12 08:00:00',
                'end_time' => '2019-03-12 14:00:00',
                'setup_time' => 0,
                'teardown_time' => 0,
                'fac_report' => 0,
                'fac_leave' => 0,
                'initial_meeting_room' => 44,
                'color' => NULL,
                'sims_spec_needed' => 0,
                'special_requirements' => 0,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-03-12 13:37:13',
                'updated_at' => '2019-03-12 13:37:13',
            ),
        ));
        
        
    }
}