<?php

use Illuminate\Database\Seeder;

class LocationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('locations')->delete();
        
        DB::table('locations')->insert(array (
            0 => 
            array (
                'id' => 8,
                'site_id' => 1,
                'building_id' => 7,
                'abbrv' => '3rd Flr',
                'name' => 'WISER Simulation Center at McKee Place',
                'more_info' => '<p>Go through the lobby of McKee Place and take the elevators to the third floor. &nbsp;Exit the elevators and go through the double glass doors in front of you.&nbsp;</p>
<p><span style="color: #ff0000;"><strong>Turn to your left and sign in at the front desk using the iPads there.&nbsp;</strong></span></p>
<p>&nbsp;</p>',
                'directions_url' => 'https://14ac05a8-a-62cb3a1a-s-sites.googlegroups.com/site/larasimsexp/clients/resources/ClassroomAB.gif?attachauth=ANoY7coaJz_oxKxqI7FzBekjJsSEJ7yeRQ4Y7KMmqFSV5uOYIzfROEv2Rl6KZdHOvqAbuDwt9xmavU9sc84RxGps84aCkWVtLCD17cNVuIYQqHobJDk9dUcyUk2G1FgQhsokfD_ByVQvcsm9dY1_TrXXkc3SSf_OEwDPazTYyoObm8iEyG5PkuKYlxMXvxa4oax0di3vJINWCds3McdmJiUWU_twQIm5RAN025xLf_342gkryXVExPU%3D&attredirects=0',
                'display_order' => '1.00',
                'html_color' => NULL,
                'retire_date' => NULL,
                'created_at' => '2018-03-08 13:40:46',
                'updated_at' => '2018-03-21 15:06:06',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 9,
                'site_id' => 1,
                'building_id' => 7,
                'abbrv' => '4 West',
                'name' => 'WISER Clinical Skills Center at McKee Place',
                'more_info' => '<p>Through the lobby. Elevators to 4. Go out of the elevators and go right to the end of the hall, and through the frosted glass door.&nbsp;</p>',
                'directions_url' => NULL,
                'display_order' => '2.00',
                'html_color' => NULL,
                'retire_date' => NULL,
                'created_at' => '2018-03-08 20:33:42',
                'updated_at' => '2018-03-21 16:39:16',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 10,
                'site_id' => 1,
                'building_id' => 16,
                'abbrv' => 'Sim Center',
                'name' => 'Simulation Center at the UPMC East Annex',
                'more_info' => '<p>Go into entrance "<strong>B</strong>" by the upper parking lot, up the steps and to the left at the first landing.&nbsp;</p>',
                'directions_url' => NULL,
                'display_order' => '1.00',
                'html_color' => '#3BFF0A',
                'retire_date' => NULL,
                'created_at' => '2018-03-08 20:36:18',
                'updated_at' => '2018-03-14 14:40:41',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 11,
                'site_id' => 1,
                'building_id' => 15,
                'abbrv' => 'Watson',
                'name' => 'Watson Center',
                'more_info' => '<p>This is on the 6th floor behind the ICU</p>',
                'directions_url' => NULL,
                'display_order' => '1.00',
                'html_color' => '#FF1F69',
                'retire_date' => NULL,
                'created_at' => '2018-03-09 02:26:19',
                'updated_at' => '2018-03-14 14:41:40',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 12,
                'site_id' => 1,
                'building_id' => 12,
                'abbrv' => 'Sim Center',
                'name' => 'CHP Sim Center',
                'more_info' => '<p>Foobar here.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>',
                'directions_url' => NULL,
                'display_order' => '1.00',
            'html_color' => 'rgba(153, 0, 255, 0.45)',
                'retire_date' => NULL,
                'created_at' => '2018-03-09 02:28:52',
                'updated_at' => '2018-03-14 18:59:05',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 13,
                'site_id' => 1,
                'building_id' => 12,
                'abbrv' => 'ER',
                'name' => 'Emergency Room Sim Center',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '2.00',
            'html_color' => 'rgba(153, 0, 255, 0.45)',
                'retire_date' => NULL,
                'created_at' => '2018-03-09 02:29:41',
                'updated_at' => '2018-03-14 18:59:16',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 14,
                'site_id' => 1,
                'building_id' => 15,
                'abbrv' => 'In-Situ',
                'name' => 'In-Situ Location',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '2.00',
                'html_color' => '#FF1F69',
                'retire_date' => NULL,
                'created_at' => '2018-03-09 02:30:18',
                'updated_at' => '2018-03-14 14:41:45',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 15,
                'site_id' => 1,
                'building_id' => 12,
                'abbrv' => 'In-Situ',
                'name' => 'In-Situ within CHP',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '3.00',
            'html_color' => 'rgba(153, 0, 255, 0.45)',
                'retire_date' => NULL,
                'created_at' => '2018-03-12 16:41:19',
                'updated_at' => '2018-03-14 18:59:28',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 16,
                'site_id' => 1,
                'building_id' => 22,
                'abbrv' => 'In-Situ',
                'name' => 'In-Situ within UPMC EAST',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '1.00',
                'html_color' => '#3BFF0A',
                'retire_date' => NULL,
                'created_at' => '2018-03-12 16:53:33',
                'updated_at' => '2018-03-14 14:01:21',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 17,
                'site_id' => 1,
                'building_id' => 8,
                'abbrv' => 'Sim Center',
                'name' => 'The WISER Simulation Center at UPMC Passavant',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '1.00',
            'html_color' => 'rgba(44, 130, 12, 0.48)',
                'retire_date' => NULL,
                'created_at' => '2018-03-12 17:17:24',
                'updated_at' => '2018-03-14 17:12:54',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 18,
                'site_id' => 1,
                'building_id' => 8,
                'abbrv' => 'In-Situ',
                'name' => 'In-Situ Location at UPMC Passavant',
                'more_info' => '<p>This is a location somewhere in Passavant. Details for the exact location will be in the information for the particular event.</p>',
                'directions_url' => NULL,
                'display_order' => '2.00',
            'html_color' => 'rgba(44, 130, 12, 0.48)',
                'retire_date' => NULL,
                'created_at' => '2018-03-12 17:19:24',
                'updated_at' => '2018-03-14 17:13:35',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 19,
                'site_id' => 1,
                'building_id' => 24,
                'abbrv' => 'SON',
                'name' => 'School of Nursing Simulation Lab',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '1.00',
                'html_color' => '#8F5D13',
                'retire_date' => '2018-03-14 15:24:12',
                'created_at' => '2018-03-14 15:20:17',
                'updated_at' => '2018-03-14 15:24:12',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 20,
                'site_id' => 1,
                'building_id' => 18,
                'abbrv' => 'In-Situ',
                'name' => 'In-Situ at UPMC Mercy',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '1.00',
            'html_color' => 'rgba(153, 0, 255, 0.36)',
                'retire_date' => NULL,
                'created_at' => '2018-03-21 15:07:22',
                'updated_at' => '2018-03-21 15:33:30',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 21,
                'site_id' => 1,
                'building_id' => 25,
                'abbrv' => 'In-Situ',
                'name' => 'In-Situ at UPMC St. Margaret',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '1.00',
            'html_color' => 'rgb(255, 165, 0)',
                'retire_date' => NULL,
                'created_at' => '2018-03-21 15:09:27',
                'updated_at' => '2018-03-21 15:35:54',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 22,
                'site_id' => 1,
                'building_id' => 9,
                'abbrv' => 'Simulation Center',
                'name' => 'Simulation Center at UPMC McKeesport',
                'more_info' => '<p>Attached to the Garage.</p>',
                'directions_url' => NULL,
                'display_order' => '1.00',
            'html_color' => 'rgba(255, 0, 0, 0.72)',
                'retire_date' => NULL,
                'created_at' => '2018-03-21 15:11:49',
                'updated_at' => '2018-03-21 15:32:39',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 23,
                'site_id' => 1,
                'building_id' => 9,
                'abbrv' => 'In-Situ',
                'name' => 'In-Situ at UPMC McKeesport',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '2.00',
            'html_color' => 'rgba(255, 0, 0, 0.72)',
                'retire_date' => NULL,
                'created_at' => '2018-03-21 15:12:22',
                'updated_at' => '2018-03-21 15:32:48',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 24,
                'site_id' => 1,
                'building_id' => 14,
                'abbrv' => 'Simulation Center',
                'name' => 'The Simulation Center at UPMC MWH',
                'more_info' => '<p>Is on the 4th floor of MWH in rooms 4225-4228</p>',
                'directions_url' => NULL,
                'display_order' => '1.00',
            'html_color' => 'rgb(255, 105, 180)',
                'retire_date' => NULL,
                'created_at' => '2018-03-21 15:15:12',
                'updated_at' => '2018-03-21 15:34:43',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 25,
                'site_id' => 1,
                'building_id' => 14,
                'abbrv' => 'In-Situ',
                'name' => 'In-Situ at UPMC MWH',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '2.00',
            'html_color' => 'rgb(255, 105, 180)',
                'retire_date' => NULL,
                'created_at' => '2018-03-21 15:15:40',
                'updated_at' => '2018-03-21 15:34:54',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 26,
                'site_id' => 1,
                'building_id' => 26,
                'abbrv' => 'Offsite',
                'name' => 'Offsite Location',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '1.00',
                'html_color' => NULL,
                'retire_date' => NULL,
                'created_at' => '2018-03-21 15:16:51',
                'updated_at' => '2018-03-21 15:16:51',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 27,
                'site_id' => 1,
                'building_id' => 11,
                'abbrv' => 'In-Situ',
                'name' => 'In-Situ at UPMC Shadyside',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '1.00',
            'html_color' => 'rgb(0, 255, 255)',
                'retire_date' => NULL,
                'created_at' => '2018-03-21 15:28:43',
                'updated_at' => '2018-03-21 15:30:37',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 28,
                'site_id' => 1,
                'building_id' => 27,
                'abbrv' => 'Simulation Center',
                'name' => 'WISER Simulation Center at UPMC Shadyside',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '1.00',
            'html_color' => 'rgb(0, 255, 255)',
                'retire_date' => NULL,
                'created_at' => '2018-03-21 15:30:23',
                'updated_at' => '2018-03-21 15:30:23',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 29,
                'site_id' => 6,
                'building_id' => 28,
                'abbrv' => 'SimTiki',
                'name' => 'SimTiki Simulation Center at the John A Burns School of Medicine.',
                'more_info' => '<p>The Center is on the second floor of the building.</p>',
                'directions_url' => NULL,
                'display_order' => '1.00',
                'html_color' => NULL,
                'retire_date' => NULL,
                'created_at' => '2018-03-21 18:02:22',
                'updated_at' => '2018-03-21 18:02:22',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 30,
                'site_id' => 6,
                'building_id' => 29,
                'abbrv' => 'In-Situ',
                'name' => 'In-Situ Simulation at Queens Hospital',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '1.00',
            'html_color' => 'rgb(255, 0, 255)',
                'retire_date' => NULL,
                'created_at' => '2018-03-21 18:03:13',
                'updated_at' => '2018-03-21 18:03:13',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 31,
                'site_id' => 6,
                'building_id' => 30,
                'abbrv' => 'In-Situ',
                'name' => 'In-Situ Simulation at Tripler Army Hospital',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '1.00',
            'html_color' => 'rgba(44, 130, 12, 0.55)',
                'retire_date' => NULL,
                'created_at' => '2018-03-21 18:06:05',
                'updated_at' => '2018-03-21 18:06:05',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 32,
                'site_id' => 6,
                'building_id' => 28,
                'abbrv' => 'JABSOM',
                'name' => 'John A Burns School of Medicine',
                'more_info' => NULL,
                'directions_url' => NULL,
                'display_order' => '2.00',
            'html_color' => NULL,
                'retire_date' => NULL,
                'created_at' => '2018-10-12 16:52:18',
                'updated_at' => '2018-10-12 16:52:18',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}