<?php

use Illuminate\Database\Seeder;

class ResourcesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('resources')->delete();
        
        \DB::table('resources')->insert(array (
            0 => 
            array (
                'id' => 1,
                'abbrv' => 'ACLS 1',
                'description' => 'ACLS/BLS Room 1',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 19,
                'resource_sub_category_id' => 42,
                'retire_date' => NULL,
                'created_by' => 4,
                'last_edited_by' => 1,
                'created_at' => NULL,
                'updated_at' => '2018-10-10 16:48:01',
            ),
            1 => 
            array (
                'id' => 7,
                'abbrv' => '3G #1',
                'description' => 'Laerdal 3G #1',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 4,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-03 14:56:43',
                'updated_at' => '2018-10-03 20:25:25',
            ),
            2 => 
            array (
                'id' => 8,
                'abbrv' => '3G #2',
                'description' => 'Laerdal 3G #2',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 4,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-03 14:59:52',
                'updated_at' => '2019-01-24 17:35:44',
            ),
            3 => 
            array (
                'id' => 9,
                'abbrv' => '3G #3',
                'description' => 'Laerdal 3G #3',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 4,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-03 15:00:37',
                'updated_at' => '2018-10-03 19:43:45',
            ),
            4 => 
            array (
                'id' => 13,
                'abbrv' => 'MET 13',
                'description' => 'Medical Education Theater 13',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 18,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-03 18:03:19',
                'updated_at' => '2018-10-10 17:15:13',
            ),
            5 => 
            array (
                'id' => 18,
                'abbrv' => 'SimMan Bob',
                'description' => 'SimMan Classic Bob',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 5,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-03 20:09:01',
                'updated_at' => '2018-10-03 20:09:01',
            ),
            6 => 
            array (
                'id' => 19,
                'abbrv' => '3G #4',
                'description' => 'Laerdal 3G #4',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 4,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-03 20:24:19',
                'updated_at' => '2018-10-03 20:38:14',
            ),
            7 => 
            array (
                'id' => 20,
                'abbrv' => 'SimMan Ted',
                'description' => 'SimMan Classic Ted',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 5,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-05 14:00:01',
                'updated_at' => '2018-10-05 14:00:01',
            ),
            8 => 
            array (
                'id' => 21,
                'abbrv' => 'SimMan Frank',
                'description' => 'SimMan Classic Frank',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 5,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-05 14:00:39',
                'updated_at' => '2018-10-05 14:00:39',
            ),
            9 => 
            array (
                'id' => 22,
                'abbrv' => 'Essential #1',
                'description' => 'SimMan Essential #1',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 6,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-05 14:01:29',
                'updated_at' => '2018-10-05 14:01:29',
            ),
            10 => 
            array (
                'id' => 23,
                'abbrv' => 'Essential #2',
                'description' => 'SimMan Essential #2',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 6,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-05 14:02:31',
                'updated_at' => '2018-10-05 14:02:31',
            ),
            11 => 
            array (
                'id' => 24,
                'abbrv' => 'Essential #3',
                'description' => 'SimMan Essential #3',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 6,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-05 14:03:11',
                'updated_at' => '2018-10-05 14:03:11',
            ),
            12 => 
            array (
                'id' => 25,
                'abbrv' => 'ALS Man #1',
                'description' => 'ALS Manikin #1',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 7,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-05 14:03:51',
                'updated_at' => '2018-10-05 14:03:51',
            ),
            13 => 
            array (
                'id' => 26,
                'abbrv' => 'ALS Man #2',
                'description' => 'ALS Manikin #2',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 7,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-05 14:04:37',
                'updated_at' => '2018-10-05 14:04:37',
            ),
            14 => 
            array (
                'id' => 27,
                'abbrv' => 'ALS Man #3',
                'description' => 'ALS Manikin #3',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 7,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-05 14:09:48',
                'updated_at' => '2018-10-05 14:09:48',
            ),
            15 => 
            array (
                'id' => 28,
                'abbrv' => 'Nancy',
                'description' => 'Noelle Simulator Nancy',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 8,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:27:35',
                'updated_at' => '2018-10-08 19:27:35',
            ),
            16 => 
            array (
                'id' => 29,
                'abbrv' => 'SimBaby #1',
                'description' => 'Laerdal SimBaby #1',
                'location_id' => 12,
                'resource_type_id' => 2,
                'resource_category_id' => 10,
                'resource_sub_category_id' => 9,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:29:45',
                'updated_at' => '2018-10-08 19:52:19',
            ),
            17 => 
            array (
                'id' => 30,
                'abbrv' => 'SimNewB #1',
                'description' => 'Laredal SimNewB #1',
                'location_id' => 12,
                'resource_type_id' => 2,
                'resource_category_id' => 10,
                'resource_sub_category_id' => 10,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:30:54',
                'updated_at' => '2018-10-08 19:53:01',
            ),
            18 => 
            array (
                'id' => 31,
                'abbrv' => 'SimJunior #1',
                'description' => 'Laerdal SimJunior',
                'location_id' => 12,
                'resource_type_id' => 2,
                'resource_category_id' => 10,
                'resource_sub_category_id' => 11,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:46:35',
                'updated_at' => '2018-10-08 19:52:45',
            ),
            19 => 
            array (
                'id' => 32,
                'abbrv' => 'Premie Anne #1',
                'description' => 'Laerdal Premie Anne',
                'location_id' => 12,
                'resource_type_id' => 2,
                'resource_category_id' => 10,
                'resource_sub_category_id' => 12,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:47:55',
                'updated_at' => '2018-10-08 19:52:33',
            ),
            20 => 
            array (
                'id' => 33,
                'abbrv' => 'Good Adult CC',
                'description' => 'Good Adult Crash Cart',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 11,
                'resource_sub_category_id' => 13,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:51:20',
                'updated_at' => '2018-10-08 19:51:20',
            ),
            21 => 
            array (
                'id' => 34,
                'abbrv' => 'Backup Adult CC',
                'description' => 'Backup Adult Crash Cart',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 11,
                'resource_sub_category_id' => 13,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:51:57',
                'updated_at' => '2018-10-08 19:51:57',
            ),
            22 => 
            array (
                'id' => 35,
                'abbrv' => 'Good Peds  CC',
                'description' => 'Good Peds Crash Cart',
                'location_id' => 12,
                'resource_type_id' => 2,
                'resource_category_id' => 11,
                'resource_sub_category_id' => 14,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:53:42',
                'updated_at' => '2019-01-24 17:35:31',
            ),
            23 => 
            array (
                'id' => 36,
                'abbrv' => 'Backup Peds  CC',
                'description' => 'Backup Peds Crash Cart',
                'location_id' => 12,
                'resource_type_id' => 2,
                'resource_category_id' => 11,
                'resource_sub_category_id' => 14,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:54:22',
                'updated_at' => '2019-01-22 19:49:37',
            ),
            24 => 
            array (
                'id' => 37,
                'abbrv' => 'Vimedex #1',
                'description' => 'Vimedex Ultrasound #1',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 12,
                'resource_sub_category_id' => 15,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:55:17',
                'updated_at' => '2018-10-08 19:55:17',
            ),
            25 => 
            array (
                'id' => 38,
                'abbrv' => 'Vimedex #2',
                'description' => 'Vimedex Ultrasound #2',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 12,
                'resource_sub_category_id' => 15,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:55:51',
                'updated_at' => '2018-10-08 19:55:51',
            ),
            26 => 
            array (
                'id' => 39,
                'abbrv' => 'Vimedex #3',
                'description' => 'Vimedex Ultrasound #3',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 12,
                'resource_sub_category_id' => 15,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:56:30',
                'updated_at' => '2018-10-08 19:56:30',
            ),
            27 => 
            array (
                'id' => 40,
                'abbrv' => 'SonoSite Old',
                'description' => 'SonoSite Old',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 12,
                'resource_sub_category_id' => 16,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:57:03',
                'updated_at' => '2018-10-08 19:57:03',
            ),
            28 => 
            array (
                'id' => 41,
                'abbrv' => 'SonoSite New',
                'description' => 'SonoSite New',
                'location_id' => 8,
                'resource_type_id' => 2,
                'resource_category_id' => 12,
                'resource_sub_category_id' => 16,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-08 19:57:32',
                'updated_at' => '2018-10-08 19:57:32',
            ),
            29 => 
            array (
                'id' => 42,
                'abbrv' => 'ACLS 2',
                'description' => 'ACLS/BLS Room 2',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 19,
                'resource_sub_category_id' => 42,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:45:42',
                'updated_at' => '2019-01-24 17:35:51',
            ),
            30 => 
            array (
                'id' => 43,
                'abbrv' => 'ACLS 3',
                'description' => 'ACLS/BLS Room 3',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 19,
                'resource_sub_category_id' => 42,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:50:40',
                'updated_at' => '2018-10-10 16:50:40',
            ),
            31 => 
            array (
                'id' => 44,
                'abbrv' => 'CL A',
                'description' => 'Classroom A',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 13,
                'resource_sub_category_id' => 27,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:51:21',
                'updated_at' => '2018-10-10 16:51:21',
            ),
            32 => 
            array (
                'id' => 45,
                'abbrv' => 'CL B',
                'description' => 'Classroom B',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 13,
                'resource_sub_category_id' => 27,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:51:47',
                'updated_at' => '2018-10-10 16:51:47',
            ),
            33 => 
            array (
                'id' => 46,
                'abbrv' => 'DB 1',
                'description' => 'Debriefing Room 1',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 18,
                'resource_sub_category_id' => 39,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:53:27',
                'updated_at' => '2018-10-10 16:53:27',
            ),
            34 => 
            array (
                'id' => 47,
                'abbrv' => 'DB 2',
                'description' => 'Debriefing Room 2',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 18,
                'resource_sub_category_id' => 40,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:53:53',
                'updated_at' => '2018-10-10 16:53:53',
            ),
            35 => 
            array (
                'id' => 48,
                'abbrv' => 'LBRY',
                'description' => 'Library',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 20,
                'resource_sub_category_id' => 43,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:55:40',
                'updated_at' => '2018-10-10 16:55:40',
            ),
            36 => 
            array (
                'id' => 49,
                'abbrv' => 'Lobby',
                'description' => 'Lobby Meeting Place',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 20,
                'resource_sub_category_id' => 45,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:56:09',
                'updated_at' => '2018-10-10 16:56:09',
            ),
            37 => 
            array (
                'id' => 50,
                'abbrv' => 'MET 1',
                'description' => 'Medical Education Theater 1',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 17,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:56:43',
                'updated_at' => '2018-10-10 16:56:43',
            ),
            38 => 
            array (
                'id' => 51,
                'abbrv' => 'MET 2',
                'description' => 'Medical Education Theater 2',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 18,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:57:07',
                'updated_at' => '2018-10-10 16:57:07',
            ),
            39 => 
            array (
                'id' => 52,
                'abbrv' => 'MET 3',
                'description' => 'Medical Education Theater 3',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 18,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:58:06',
                'updated_at' => '2018-10-10 16:58:06',
            ),
            40 => 
            array (
                'id' => 53,
                'abbrv' => 'MET 4',
                'description' => 'Medical Education Theater 4',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 18,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 16:58:37',
                'updated_at' => '2018-10-10 16:58:37',
            ),
            41 => 
            array (
                'id' => 54,
                'abbrv' => 'MET 5',
                'description' => 'Medical Education Theater 5',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 18,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:02:28',
                'updated_at' => '2018-10-10 17:02:28',
            ),
            42 => 
            array (
                'id' => 55,
                'abbrv' => 'MET 6',
                'description' => 'Medical Education Theater 6',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 18,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:04:08',
                'updated_at' => '2018-10-10 17:04:24',
            ),
            43 => 
            array (
                'id' => 56,
                'abbrv' => 'MET 7',
                'description' => 'Medical Education Theater 7',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 18,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:04:48',
                'updated_at' => '2018-10-10 17:04:48',
            ),
            44 => 
            array (
                'id' => 57,
                'abbrv' => 'MET 8',
                'description' => 'Medical Education Theater 8',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 17,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:05:14',
                'updated_at' => '2018-10-10 17:05:14',
            ),
            45 => 
            array (
                'id' => 58,
                'abbrv' => 'MET 9',
                'description' => 'Medical Education Theater 9',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 17,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:05:34',
                'updated_at' => '2018-10-10 17:05:34',
            ),
            46 => 
            array (
                'id' => 59,
                'abbrv' => 'MPL 1',
                'description' => 'Medical Procedures Lab 1',
                'location_id' => 8,
                'resource_type_id' => 1,
                'resource_category_id' => 21,
                'resource_sub_category_id' => 48,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:07:08',
                'updated_at' => '2018-10-10 17:24:03',
            ),
            47 => 
            array (
                'id' => 60,
                'abbrv' => 'Met 12',
                'description' => 'Medical Education Theater 12',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 17,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:08:04',
                'updated_at' => '2018-10-10 17:08:04',
            ),
            48 => 
            array (
                'id' => 61,
                'abbrv' => 'MET 14',
                'description' => 'Medical Education Theater 14',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 18,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:09:24',
                'updated_at' => '2018-10-10 17:15:35',
            ),
            49 => 
            array (
                'id' => 62,
                'abbrv' => 'MET 15',
                'description' => 'Medical Education Theater 15',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 17,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:09:52',
                'updated_at' => '2018-10-10 17:14:51',
            ),
            50 => 
            array (
                'id' => 63,
                'abbrv' => 'MET 16',
                'description' => 'Medical Education Theater 16',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 17,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:10:24',
                'updated_at' => '2018-10-10 17:10:24',
            ),
            51 => 
            array (
                'id' => 64,
                'abbrv' => 'MET 17',
                'description' => 'Medical Education Theater 17',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 17,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:11:01',
                'updated_at' => '2018-10-10 17:11:01',
            ),
            52 => 
            array (
                'id' => 65,
                'abbrv' => 'MET 18',
                'description' => 'Medical Education Theater 18',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 17,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:11:27',
                'updated_at' => '2018-10-10 17:11:27',
            ),
            53 => 
            array (
                'id' => 66,
                'abbrv' => 'MET 19',
                'description' => 'Medical Education Theater 19',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 18,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:11:59',
                'updated_at' => '2018-10-10 17:11:59',
            ),
            54 => 
            array (
                'id' => 67,
                'abbrv' => 'MET 20',
                'description' => 'Medical Education Theater 20',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 17,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:12:32',
                'updated_at' => '2018-10-10 17:12:32',
            ),
            55 => 
            array (
                'id' => 68,
                'abbrv' => 'MET 21',
                'description' => 'Medical Education Theater 21',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 18,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:13:01',
                'updated_at' => '2018-10-10 17:13:01',
            ),
            56 => 
            array (
                'id' => 69,
                'abbrv' => 'MET 22',
                'description' => 'Medical Education Theater 22',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 6,
                'resource_sub_category_id' => 17,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:13:28',
                'updated_at' => '2018-10-10 17:13:28',
            ),
            57 => 
            array (
                'id' => 70,
                'abbrv' => 'CL C',
                'description' => 'Classroom C',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 13,
                'resource_sub_category_id' => 27,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:14:31',
                'updated_at' => '2018-10-10 17:14:31',
            ),
            58 => 
            array (
                'id' => 71,
                'abbrv' => 'DB 3',
                'description' => 'Debriefing Room 3',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 18,
                'resource_sub_category_id' => 40,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:16:35',
                'updated_at' => '2018-10-10 17:16:35',
            ),
            59 => 
            array (
                'id' => 72,
                'abbrv' => 'CONF 4-A',
                'description' => 'Conference Room 4-A',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 22,
                'resource_sub_category_id' => 46,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:18:28',
                'updated_at' => '2018-10-10 17:18:28',
            ),
            60 => 
            array (
                'id' => 73,
                'abbrv' => 'Tele-Conf',
                'description' => 'Tele Conference Room',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 22,
                'resource_sub_category_id' => 46,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:19:13',
                'updated_at' => '2018-10-10 17:19:13',
            ),
            61 => 
            array (
                'id' => 74,
                'abbrv' => 'Visit Scholar',
                'description' => 'Visiting Scholar Room',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 22,
                'resource_sub_category_id' => 47,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:20:00',
                'updated_at' => '2018-10-10 17:20:00',
            ),
            62 => 
            array (
                'id' => 75,
                'abbrv' => '4th PGM',
                'description' => 'Programming Room',
                'location_id' => 9,
                'resource_type_id' => 1,
                'resource_category_id' => 20,
                'resource_sub_category_id' => 43,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:20:38',
                'updated_at' => '2018-10-10 17:20:38',
            ),
            63 => 
            array (
                'id' => 76,
                'abbrv' => 'SimLab',
                'description' => 'Simulation Lab',
                'location_id' => 12,
                'resource_type_id' => 1,
                'resource_category_id' => 21,
                'resource_sub_category_id' => 49,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:25:07',
                'updated_at' => '2018-11-05 15:34:48',
            ),
            64 => 
            array (
                'id' => 77,
                'abbrv' => 'PSV-LAB 1',
                'description' => 'Passavant Lab 1',
                'location_id' => 17,
                'resource_type_id' => 1,
                'resource_category_id' => 21,
                'resource_sub_category_id' => 49,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:30:44',
                'updated_at' => '2018-10-10 17:30:44',
            ),
            65 => 
            array (
                'id' => 78,
                'abbrv' => 'PSV-LAB 2',
                'description' => 'Passavant Lab 2',
                'location_id' => 17,
                'resource_type_id' => 1,
                'resource_category_id' => 21,
                'resource_sub_category_id' => 49,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:31:26',
                'updated_at' => '2018-10-10 17:31:26',
            ),
            66 => 
            array (
                'id' => 79,
                'abbrv' => 'PSV-Classroom',
                'description' => 'Passavant Classroom',
                'location_id' => 17,
                'resource_type_id' => 1,
                'resource_category_id' => 13,
                'resource_sub_category_id' => 27,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:32:12',
                'updated_at' => '2018-10-10 17:32:12',
            ),
            67 => 
            array (
                'id' => 80,
                'abbrv' => 'Stretcher 1',
                'description' => 'Transport Stretcher 1',
                'location_id' => 9,
                'resource_type_id' => 2,
                'resource_category_id' => 24,
                'resource_sub_category_id' => 50,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:36:18',
                'updated_at' => '2018-10-10 17:36:18',
            ),
            68 => 
            array (
                'id' => 81,
                'abbrv' => 'Stretcher 2',
                'description' => 'Transport Stretcher 2',
                'location_id' => 9,
                'resource_type_id' => 2,
                'resource_category_id' => 24,
                'resource_sub_category_id' => 50,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-10 17:36:59',
                'updated_at' => '2018-10-10 17:36:59',
            ),
            69 => 
            array (
                'id' => 82,
                'abbrv' => 'Comp Lab',
                'description' => 'Computer Lab',
                'location_id' => 29,
                'resource_type_id' => 1,
                'resource_category_id' => 25,
                'resource_sub_category_id' => 51,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-11 16:58:40',
                'updated_at' => '2018-10-11 16:58:40',
            ),
            70 => 
            array (
                'id' => 83,
                'abbrv' => 'Conf Room',
                'description' => 'Conference Room',
                'location_id' => 29,
                'resource_type_id' => 1,
                'resource_category_id' => 26,
                'resource_sub_category_id' => 53,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-11 16:59:57',
                'updated_at' => '2018-10-11 16:59:57',
            ),
            71 => 
            array (
                'id' => 84,
                'abbrv' => 'Control',
                'description' => 'Control Room',
                'location_id' => 29,
                'resource_type_id' => 1,
                'resource_category_id' => 28,
                'resource_sub_category_id' => 59,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-11 17:00:30',
                'updated_at' => '2018-10-11 17:00:30',
            ),
            72 => 
            array (
                'id' => 85,
                'abbrv' => 'SimRoom 1',
                'description' => 'Simulation Room 1',
                'location_id' => 29,
                'resource_type_id' => 1,
                'resource_category_id' => 32,
                'resource_sub_category_id' => 63,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:07:14',
                'updated_at' => '2018-10-12 16:07:14',
            ),
            73 => 
            array (
                'id' => 86,
                'abbrv' => 'SimRoom 2',
                'description' => 'Simulation Room 2',
                'location_id' => 29,
                'resource_type_id' => 1,
                'resource_category_id' => 32,
                'resource_sub_category_id' => 64,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:07:37',
                'updated_at' => '2018-10-12 16:07:37',
            ),
            74 => 
            array (
                'id' => 87,
                'abbrv' => 'SimRoom 3',
                'description' => 'Simulation Room 3',
                'location_id' => 29,
                'resource_type_id' => 1,
                'resource_category_id' => 32,
                'resource_sub_category_id' => 65,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:08:02',
                'updated_at' => '2018-10-12 16:08:02',
            ),
            75 => 
            array (
                'id' => 88,
                'abbrv' => 'TRI 2nd Lobby',
                'description' => 'TRI 2nd Floor Lobby',
                'location_id' => 29,
                'resource_type_id' => 1,
                'resource_category_id' => 28,
                'resource_sub_category_id' => 58,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:08:43',
                'updated_at' => '2018-10-12 16:08:43',
            ),
            76 => 
            array (
                'id' => 89,
                'abbrv' => '#1 Airway Trainer',
                'description' => '#1 Airway Management Trainer',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 29,
                'resource_sub_category_id' => 60,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:10:03',
                'updated_at' => '2018-10-12 16:10:03',
            ),
            77 => 
            array (
                'id' => 90,
                'abbrv' => '#2 Airway Trainer',
                'description' => '#2 Airway Management Trainer',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 29,
                'resource_sub_category_id' => 60,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:10:34',
                'updated_at' => '2018-10-12 16:10:34',
            ),
            78 => 
            array (
                'id' => 91,
                'abbrv' => '#3 Airway Trainer',
                'description' => '#3 Airway Management Trainer',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 29,
                'resource_sub_category_id' => 60,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:11:00',
                'updated_at' => '2018-10-12 16:11:00',
            ),
            79 => 
            array (
                'id' => 92,
                'abbrv' => '#4 Airway Trainer',
                'description' => '#4 Airway Management Trainer',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 29,
                'resource_sub_category_id' => 60,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:11:22',
                'updated_at' => '2018-10-12 16:11:22',
            ),
            80 => 
            array (
                'id' => 93,
                'abbrv' => '#1 Defibrillator',
            'description' => '#1 Defibrillator Zoll (w/Hands Free)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 30,
                'resource_sub_category_id' => 66,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:12:55',
                'updated_at' => '2018-10-12 16:13:35',
            ),
            81 => 
            array (
                'id' => 94,
                'abbrv' => '#2 Defibrillator',
            'description' => '#2 Defibrillator Zoll (w/Hands Free)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 30,
                'resource_sub_category_id' => 66,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:14:18',
                'updated_at' => '2018-10-12 16:14:18',
            ),
            82 => 
            array (
                'id' => 95,
                'abbrv' => '#3 Defibrillator',
            'description' => '#3 Defibrillator Zoll (w/Hands Free)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 30,
                'resource_sub_category_id' => 66,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:14:46',
                'updated_at' => '2018-10-12 16:14:46',
            ),
            83 => 
            array (
                'id' => 96,
                'abbrv' => '#4 Defibrillator',
            'description' => '#4 Defibrillator Zoll (w/Hands Free)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 30,
                'resource_sub_category_id' => 66,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:16:07',
                'updated_at' => '2018-10-12 16:16:07',
            ),
            84 => 
            array (
                'id' => 97,
                'abbrv' => '#1 Crash Cart',
            'description' => '#1 Crash Cart (w/Hands Free Defib)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 33,
                'resource_sub_category_id' => 67,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:20:06',
                'updated_at' => '2018-10-12 16:20:06',
            ),
            85 => 
            array (
                'id' => 98,
                'abbrv' => '#2 Crash Cart',
            'description' => '#2 Crash Cart (w/Hands Free Defib)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 33,
                'resource_sub_category_id' => 67,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:20:30',
                'updated_at' => '2018-10-12 16:20:30',
            ),
            86 => 
            array (
                'id' => 99,
                'abbrv' => '#3 Crash Cart',
            'description' => '#3 Crash Cart (w/Hands Free Defib)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 33,
                'resource_sub_category_id' => 67,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:20:54',
                'updated_at' => '2018-10-12 16:20:54',
            ),
            87 => 
            array (
                'id' => 100,
                'abbrv' => '#4 Crash Cart',
            'description' => '#4 Crash Cart (w/Hands Free Defib)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 33,
                'resource_sub_category_id' => 67,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:21:27',
                'updated_at' => '2018-10-12 16:21:27',
            ),
            88 => 
            array (
                'id' => 101,
                'abbrv' => '#5 MH Crash Cart',
            'description' => '#5 MH Crash Cart (MH vials, syringes, airway)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 33,
                'resource_sub_category_id' => 68,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:22:30',
                'updated_at' => '2018-10-12 16:22:30',
            ),
            89 => 
            array (
                'id' => 102,
                'abbrv' => 'Bronchoscopy Trainer',
            'description' => 'Bronchoscopy Trainer (Adult/Ped)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 31,
                'resource_sub_category_id' => 61,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:23:25',
                'updated_at' => '2018-10-12 16:23:25',
            ),
            90 => 
            array (
                'id' => 103,
                'abbrv' => 'Colonoscopy/EGD',
            'description' => 'Colonoscopy/EGD (Adult)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 31,
                'resource_sub_category_id' => 62,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:24:18',
                'updated_at' => '2018-10-12 16:24:18',
            ),
            91 => 
            array (
                'id' => 104,
                'abbrv' => '3G',
                'description' => '3G SimMan',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 34,
                'resource_sub_category_id' => 74,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:35:15',
                'updated_at' => '2018-10-12 16:35:15',
            ),
            92 => 
            array (
                'id' => 105,
                'abbrv' => 'ALS',
                'description' => 'ALS Manikin',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 34,
                'resource_sub_category_id' => 70,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:35:37',
                'updated_at' => '2018-10-12 16:35:37',
            ),
            93 => 
            array (
                'id' => 106,
                'abbrv' => 'Essential #1',
                'description' => 'Essential #1 Manikin',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 34,
                'resource_sub_category_id' => 71,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:36:22',
                'updated_at' => '2018-10-12 16:36:22',
            ),
            94 => 
            array (
                'id' => 107,
                'abbrv' => 'Essential #2',
                'description' => 'Essential #2 Manikin',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 34,
                'resource_sub_category_id' => 71,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:37:42',
                'updated_at' => '2018-10-12 16:37:42',
            ),
            95 => 
            array (
                'id' => 108,
                'abbrv' => 'Pelvic #1',
                'description' => 'Pelvic Exam Simulator #1',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 34,
                'resource_sub_category_id' => 72,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:38:15',
                'updated_at' => '2018-10-12 16:38:15',
            ),
            96 => 
            array (
                'id' => 109,
                'abbrv' => 'Pelvic #2',
                'description' => 'Pelvic Exam Simulator #2',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 34,
                'resource_sub_category_id' => 72,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:38:41',
                'updated_at' => '2018-10-12 16:38:41',
            ),
            97 => 
            array (
                'id' => 110,
                'abbrv' => 'SimBaby #1',
                'description' => 'SimBaby #1',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 34,
                'resource_sub_category_id' => 73,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:39:04',
                'updated_at' => '2018-10-12 16:39:17',
            ),
            98 => 
            array (
                'id' => 111,
                'abbrv' => 'SimBaby #2',
                'description' => 'SimBaby #2',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 34,
                'resource_sub_category_id' => 73,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:39:45',
                'updated_at' => '2018-10-12 16:39:45',
            ),
            99 => 
            array (
                'id' => 112,
                'abbrv' => 'SimMan #1',
                'description' => 'SimMan #1',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 34,
                'resource_sub_category_id' => 74,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:40:10',
                'updated_at' => '2018-10-12 16:40:10',
            ),
            100 => 
            array (
                'id' => 113,
                'abbrv' => 'SimMan #2',
                'description' => 'SimMan #2',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 34,
                'resource_sub_category_id' => 74,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:40:44',
                'updated_at' => '2018-10-12 16:40:44',
            ),
            101 => 
            array (
                'id' => 114,
                'abbrv' => 'FLS Box #1',
                'description' => 'FLS Box Practice #1',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 35,
                'resource_sub_category_id' => 76,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:41:27',
                'updated_at' => '2018-10-12 16:41:27',
            ),
            102 => 
            array (
                'id' => 115,
                'abbrv' => 'FLS Box #2',
                'description' => 'FLS Box Practice #2',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 35,
                'resource_sub_category_id' => 76,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:41:51',
                'updated_at' => '2018-10-12 16:41:51',
            ),
            103 => 
            array (
                'id' => 116,
                'abbrv' => 'Lap VR - CAE',
            'description' => 'Lap VR - CAE (Used for Physician Training)',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 35,
                'resource_sub_category_id' => 77,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:42:16',
                'updated_at' => '2018-10-12 16:42:16',
            ),
            104 => 
            array (
                'id' => 117,
                'abbrv' => 'LapSim',
                'description' => 'LapSim Tour Only',
                'location_id' => 29,
                'resource_type_id' => 2,
                'resource_category_id' => 35,
                'resource_sub_category_id' => 78,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:42:48',
                'updated_at' => '2018-10-12 16:42:48',
            ),
            105 => 
            array (
                'id' => 118,
                'abbrv' => '217 - CE',
                'description' => '217 Clinical Exam Room',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 36,
                'resource_sub_category_id' => 79,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:45:59',
                'updated_at' => '2018-10-12 16:53:09',
            ),
            106 => 
            array (
                'id' => 119,
                'abbrv' => '224 - EWA [12]',
            'description' => '224 - EWA Conference Room (12)',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 26,
                'resource_sub_category_id' => 53,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:55:30',
                'updated_at' => '2018-10-12 16:55:58',
            ),
            107 => 
            array (
                'id' => 120,
                'abbrv' => '301 - DH [74]',
                'description' => 'Classroom 301',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 27,
                'resource_sub_category_id' => 57,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 16:59:13',
                'updated_at' => '2018-10-12 17:01:10',
            ),
            108 => 
            array (
                'id' => 121,
                'abbrv' => '302 - DH [30]',
                'description' => 'Classroom 302',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 27,
                'resource_sub_category_id' => 56,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:00:17',
                'updated_at' => '2018-10-12 17:00:17',
            ),
            109 => 
            array (
                'id' => 122,
                'abbrv' => '304 - DH [74]',
                'description' => 'Classroom 304',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 27,
                'resource_sub_category_id' => 57,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:01:46',
                'updated_at' => '2018-10-12 17:01:46',
            ),
            110 => 
            array (
                'id' => 123,
                'abbrv' => '305 B - DH [12]',
                'description' => 'Conference Room 305 B',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 26,
                'resource_sub_category_id' => 52,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:03:14',
                'updated_at' => '2018-10-12 17:03:14',
            ),
            111 => 
            array (
                'id' => 124,
                'abbrv' => '314-1/314-2 [40]',
                'description' => 'Classroom 314',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 27,
                'resource_sub_category_id' => 57,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:03:57',
                'updated_at' => '2018-10-12 17:03:57',
            ),
            112 => 
            array (
                'id' => 125,
                'abbrv' => '315 - Aud [150]',
                'description' => 'MEB Auditorium 315',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 37,
                'resource_sub_category_id' => 80,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:05:58',
                'updated_at' => '2018-10-12 17:05:58',
            ),
            113 => 
            array (
                'id' => 126,
                'abbrv' => '410 - DH [12]',
                'description' => 'Conference Room 410',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 26,
                'resource_sub_category_id' => 52,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:06:49',
                'updated_at' => '2018-10-12 17:06:49',
            ),
            114 => 
            array (
                'id' => 127,
                'abbrv' => 'Access Grid 202 [28]',
                'description' => 'Access Grid 202',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 28,
                'resource_sub_category_id' => 59,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:08:16',
                'updated_at' => '2018-10-12 17:08:16',
            ),
            115 => 
            array (
                'id' => 128,
                'abbrv' => 'CCS 203 [12]',
                'description' => 'Clinical Skills 203',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 36,
                'resource_sub_category_id' => 79,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:09:41',
                'updated_at' => '2018-10-12 17:09:41',
            ),
            116 => 
            array (
                'id' => 129,
                'abbrv' => 'CCS 204 [10]',
                'description' => 'Clinical Skills 204',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 36,
                'resource_sub_category_id' => 79,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:10:14',
                'updated_at' => '2018-10-12 17:10:14',
            ),
            117 => 
            array (
                'id' => 130,
                'abbrv' => 'CCS 207 Vol Prep [20]',
                'description' => 'CCS 207 Vol Prep',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 36,
                'resource_sub_category_id' => 79,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:11:08',
                'updated_at' => '2018-10-12 17:11:08',
            ),
            118 => 
            array (
                'id' => 131,
                'abbrv' => 'CCS Exam D',
                'description' => 'CCS Exam Roon 205 D',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 36,
                'resource_sub_category_id' => 79,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:11:55',
                'updated_at' => '2018-10-12 17:11:55',
            ),
            119 => 
            array (
                'id' => 132,
                'abbrv' => 'Comp Lab Med Lbry',
                'description' => 'Computer Lab Med Library',
                'location_id' => 32,
                'resource_type_id' => 1,
                'resource_category_id' => 25,
                'resource_sub_category_id' => 51,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:12:38',
                'updated_at' => '2018-10-12 17:12:38',
            ),
            120 => 
            array (
                'id' => 133,
                'abbrv' => 'CVC Child US',
                'description' => 'CVS Child Ultrasound',
                'location_id' => 32,
                'resource_type_id' => 2,
                'resource_category_id' => 38,
                'resource_sub_category_id' => 83,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:14:38',
                'updated_at' => '2018-10-12 17:14:38',
            ),
            121 => 
            array (
                'id' => 134,
                'abbrv' => 'LP Baby',
                'description' => 'LP Baby Simulab',
                'location_id' => 32,
                'resource_type_id' => 2,
                'resource_category_id' => 38,
                'resource_sub_category_id' => 84,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:15:05',
                'updated_at' => '2018-10-12 17:15:05',
            ),
            122 => 
            array (
                'id' => 135,
                'abbrv' => 'ED',
                'description' => 'Emergency Department',
                'location_id' => 30,
                'resource_type_id' => 1,
                'resource_category_id' => 28,
                'resource_sub_category_id' => NULL,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:15:41',
                'updated_at' => '2018-10-12 17:15:41',
            ),
            123 => 
            array (
                'id' => 136,
                'abbrv' => 'Army Med Center',
                'description' => 'Army Medical Center',
                'location_id' => 31,
                'resource_type_id' => 1,
                'resource_category_id' => 28,
                'resource_sub_category_id' => NULL,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:16:36',
                'updated_at' => '2018-10-12 17:16:36',
            ),
            124 => 
            array (
                'id' => 137,
                'abbrv' => 'BB',
                'description' => 'Benjamin Berg',
                'location_id' => 29,
                'resource_type_id' => 3,
                'resource_category_id' => 39,
                'resource_sub_category_id' => 85,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:18:28',
                'updated_at' => '2018-10-12 17:18:28',
            ),
            125 => 
            array (
                'id' => 138,
                'abbrv' => 'KH',
                'description' => 'Kris Hara',
                'location_id' => 32,
                'resource_type_id' => 3,
                'resource_category_id' => 39,
                'resource_sub_category_id' => 86,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:18:47',
                'updated_at' => '2018-10-12 17:18:47',
            ),
            126 => 
            array (
                'id' => 139,
                'abbrv' => 'JM',
                'description' => 'Jon Mazur',
                'location_id' => 8,
                'resource_type_id' => 3,
                'resource_category_id' => 40,
                'resource_sub_category_id' => NULL,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:30:07',
                'updated_at' => '2018-10-12 17:30:07',
            ),
            127 => 
            array (
                'id' => 140,
                'abbrv' => 'CC',
                'description' => 'Clinton Clegg',
                'location_id' => 8,
                'resource_type_id' => 3,
                'resource_category_id' => 40,
                'resource_sub_category_id' => NULL,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:30:49',
                'updated_at' => '2018-10-12 17:30:49',
            ),
            128 => 
            array (
                'id' => 141,
                'abbrv' => 'MM',
                'description' => 'Martin Mayer',
                'location_id' => 8,
                'resource_type_id' => 3,
                'resource_category_id' => 40,
                'resource_sub_category_id' => NULL,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:31:09',
                'updated_at' => '2018-10-12 17:31:09',
            ),
            129 => 
            array (
                'id' => 142,
                'abbrv' => 'WC',
                'description' => 'Walter Chukwu',
                'location_id' => 8,
                'resource_type_id' => 3,
                'resource_category_id' => 40,
                'resource_sub_category_id' => NULL,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:31:27',
                'updated_at' => '2018-10-12 17:31:27',
            ),
            130 => 
            array (
                'id' => 143,
                'abbrv' => 'MR',
                'description' => 'Mike Rodgers',
                'location_id' => 8,
                'resource_type_id' => 3,
                'resource_category_id' => 40,
                'resource_sub_category_id' => NULL,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:31:46',
                'updated_at' => '2018-10-12 17:31:46',
            ),
            131 => 
            array (
                'id' => 144,
                'abbrv' => 'JC',
                'description' => 'Jason Cruz',
                'location_id' => 8,
                'resource_type_id' => 3,
                'resource_category_id' => 40,
                'resource_sub_category_id' => NULL,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:32:11',
                'updated_at' => '2018-10-12 17:32:11',
            ),
            132 => 
            array (
                'id' => 145,
                'abbrv' => 'JL',
                'description' => 'James Lightner',
                'location_id' => 8,
                'resource_type_id' => 3,
                'resource_category_id' => 40,
                'resource_sub_category_id' => NULL,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-12 17:32:51',
                'updated_at' => '2018-10-12 17:32:51',
            ),
            133 => 
            array (
                'id' => 146,
                'abbrv' => 'Test',
                'description' => 'Test Descp',
                'location_id' => 9,
                'resource_type_id' => 2,
                'resource_category_id' => 8,
                'resource_sub_category_id' => 4,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2018-10-29 16:04:17',
                'updated_at' => '2018-10-29 16:04:17',
            ),
            134 => 
            array (
                'id' => 147,
                'abbrv' => 'East SimLab',
                'description' => 'East Simulation Lab',
                'location_id' => 10,
                'resource_type_id' => 1,
                'resource_category_id' => 21,
                'resource_sub_category_id' => 49,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-22 19:49:24',
                'updated_at' => '2019-01-22 19:49:24',
            ),
            135 => 
            array (
                'id' => 148,
                'abbrv' => 'SDY-1',
                'description' => 'Shadyside 1',
                'location_id' => 27,
                'resource_type_id' => 1,
                'resource_category_id' => 19,
                'resource_sub_category_id' => 42,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 13:46:39',
                'updated_at' => '2019-01-24 13:46:39',
            ),
            136 => 
            array (
                'id' => 149,
                'abbrv' => 'MKS Classroom',
                'description' => 'MKS Classroom',
                'location_id' => 22,
                'resource_type_id' => 1,
                'resource_category_id' => 13,
                'resource_sub_category_id' => 27,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:07:49',
                'updated_at' => '2019-01-24 14:07:49',
            ),
            137 => 
            array (
                'id' => 150,
                'abbrv' => '4225 L&D',
                'description' => '4225 Labor & Delivery',
                'location_id' => 25,
                'resource_type_id' => 1,
                'resource_category_id' => 20,
                'resource_sub_category_id' => NULL,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 14:23:19',
                'updated_at' => '2019-01-24 14:23:19',
            ),
            138 => 
            array (
                'id' => 151,
                'abbrv' => 'SMH Sim1',
                'description' => 'Simulation Room 1',
                'location_id' => 21,
                'resource_type_id' => 1,
                'resource_category_id' => 21,
                'resource_sub_category_id' => 49,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:00:22',
                'updated_at' => '2019-01-24 17:00:22',
            ),
            139 => 
            array (
                'id' => 152,
                'abbrv' => 'SMH DB-1',
                'description' => 'Debriefing Room 1',
                'location_id' => 21,
                'resource_type_id' => 1,
                'resource_category_id' => 18,
                'resource_sub_category_id' => 39,
                'retire_date' => NULL,
                'created_by' => 1,
                'last_edited_by' => 1,
                'created_at' => '2019-01-24 17:01:02',
                'updated_at' => '2019-01-24 17:01:02',
            ),
        ));
        
        
    }
}