version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export TAGNAME=$(git describe --tag)
      - docker build -f ./.docker/Dockerfile .

